config/routes.rb
Rails.application.routes.draw do
	root 'home#index'
  get '/find', to: 'home#search'
  post '/find', to: 'home#result'
  get '/update', to: 'home#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto_currency.rb
class CryptoCurrency < ApplicationRecord
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def search
  	@all_currencies = CryptoCurrency.all
  end

  def result
  	@currency = CryptoCurrency.find(params[:format].to_i)
  end

  def update
  	ScrapperCrypto.new.perform
  	redirect_to find_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<br><br><br><br><br><br><br><br><br>
<div class="row justify-content-center">
	<%= link_to 'Get the latest values', update_path, class:"btn btn-primary btn-lg " %>
</div>

app/views/home/result.html.erb
<br><br><br><br><br><br><br><br><br>

<h3 class="text-center">Here is the value of your Crypto</h3><br>
<br><br>

<h5 class="text-center"><%= @currency.name %></h5>
<blockquote class="blockquote text-center">
 <p class="mb-0">$<%= @currency.value %></p>

app/views/home/search.html.erb
<br><br><br><br><br><br><br><br>

<div class="row justify-content-center">
	<div class="dropdown">
	  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    Search for Crypto
	  </button>
	  <div class="dropdown-menu right" aria-labelledby="dropdownMenuButton">
	  	<% @all_currencies.each do |currency| %>
	  		<%= link_to currency.name, find_path(currency.id), method: :post, class:"dropdown-item" %>
	    <% end %>
	  </div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/find">CryptoSearchApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/find">New crypto search<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoScrapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>